version: "3.7"
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
    environment:
      BUNDLE_PATH: vendor/bundle
      MYSQL_HOST: db
      HOST: 0.0.0.0
      IMAGEPROXY_KEY: ${IMAGEPROXY_KEY:-secret}
      IMAGEPROXY_HOST: ${IMAGEPROXY_HOST:-http://localhost:8080}
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: /bin/sh -c "bundle exec rails s"

  db:
    image: mysql:5.7.30
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - "database:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password

  imageproxy:
    image: willnorris/imageproxy
    ports:
      - "8080:8080"
    command: -addr 0.0.0.0:8080 -cache memory:200:4h -signatureKey ${IMAGEPROXY_KEY:-"secret"}

volumes:
  bundle:
  node_modules:
  database:
